WIP a workable stan.sh for k3s single node deployment
instana/lab-self-hosting-k8s pull request #10
Opened 2021-09-16 14:18 UTC by frankwg

# Why ?
We want to have only one deployment model to reduce our overall maintenance effort. K3s provides us the opportunity for single node k8s deployment, replacing the current docker based approach.

Single node deployment helps development, unit testing, also our support staffs reproducing customer's problem for better serviceability.

With proper design and arrangement, our customers can expand to multiple node deployment without much migration effort.

# What?
There are three tiers (k3s, db and instana) of deployment.
You can start with
```console
# Installing docker and k3s
./stan.sh up k3s 

# Installing instana console and the datastore layer
./stan.sh up db

# Installing instana kubectl plugin and pods of Core and Unit
./stan.sh up instana
```
all of these instructions can take an optional parameter to specific which version to be used.

You can use
```console
./stan.sh down instana
./stan.sh down db
./stan.sh down k3s
```
to restore your machine back to it original state.to restore your machine back to it original state.

2021-09-16 14:37 UTC, frankwg commented
This PR should resolve the issue https://github.com/instana/lab-self-hosting-k8s/issues/8

2021-09-20 06:03 UTC, unguiculus requested changes
I only did a quick review. I haven't really looked at the script yet.

2021-09-22 01:50 UTC, frankwg commented on .gitignore
> +.cache
This has been fixed in the commit ae4d1c285363468567fc17cbd74f3fb4b7ae234a.

2021-09-22 01:51 UTC, frankwg commented on k3s-install/conf/ambassador-service.yaml
> +     targetPort: 8443
This has been fixed in the commit ae4d1c285363468567fc17cbd74f3fb4b7ae234a.

2021-09-22 02:24 UTC, frankwg commented on k3s-install/conf/ambassador-rbac.yaml
> +# GENERATED FILE: edits made by hand will not be preserved.
Actually, I don't know how to use Traefik (sweat...).  There is no good document or example to follow through. Ambassador is way much easier to use in this example https://rancher.com/blog/2020/deploy-an-ingress-controllers. Maybe, I will change it to use Traefik in the future, if time permitted.

2021-09-22 03:10 UTC, morningspace commented
I think there is still one thing may need to be clarified. Ideally, from user's perspective, they may not need to know the details about which Kubernetes distribution is being used underneath for this Instana sandbox. No matter it is k3s or kind, the only thing that user cares about is to launch a small sandbox for Instana quickly. With that, I think maybe we should combine this into the kind-based one, instead of creating two different folders to avoid confusion.

2021-11-25 01:34 UTC, merged